# Generated by Django 2.2.6 on 2019-10-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
